services:
  sigep:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://username:password@db:5432/sigep_production
      - SECRET_KEY_BASE=your_secret_key_base
    depends_on:
      - db
    volumes:
      - .:/app
    command: bundle exec rails server -b 0.0.0.0 -p 3000
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sigep_production
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
