name: "sigep-application"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    depends_on:
    - postgres
    - selenium
    - redis

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

  postgres:
    image: postgres:latest
    command: postgres -c "pg_stat_statements.track=all" -c "shared_preload_libraries=pg_stat_statements"
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
  
  redis:
    image: redis:7.2
    restart: unless-stopped
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  memcached:
    image: memcached:latest
    restart: unless-stopped
    command: ["-m", "1024"]

volumes:
  postgres-data:
  redis-data:
  memcached-data: